services:
  postgres:
    image: postgres:16
    container_name: postgres_museos
    restart: always
    environment:
      POSTGRES_DB: museos_db
      POSTGRES_USER: museos_user
      POSTGRES_PASSWORD: museos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: